function [Node,Load,Ph1,Ph2,Ph3,Ph4,Ph5,Ph6] = importloads(filename)
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/hafez/Documents/MATLAB/Comprehensive-modeling-three-phase/ieee-37-open-dss/IEEE-37 feeder data/Spot Loads.xls
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/05/05 02:34:32

%% Import the data
[~, ~, raw] = xlsread(filename,'Sheet1');
raw = raw(5:29,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,2);
raw = raw(:,[1,3,4,5,6,7,8]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Node = data(:,1);
Load = cellVectors(:,1);
Ph1 = data(:,2);
Ph2 = data(:,3);
Ph3 = data(:,4);
Ph4 = data(:,5);
Ph5 = data(:,6);
Ph6 = data(:,7);

%% Clear temporary variables
clearvars data raw cellVectors;