function [Node,PhA,PhB,PhC] = importcapacitors(filename)%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/hafez/Documents/MATLAB/Comprehensive-modeling-three-phase/ieee-123-open-dss/IEEE-123 feeder data/cap data.xls
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/05/05 04:01:08

%% Import the data
[~, ~, raw] = xlsread(filename,'Sheet1');
raw = raw(5:8,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Node = data(:,1);
PhA = data(:,2);
PhB = data(:,3);
PhC = data(:,4);

%% Clear temporary variables
clearvars data raw R;