function [Name,phases,bus1,bus2,kV_pri,kV_sec,MVA,Conn_pri,Conn_sec,XHL,RHL] = importtransformers(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [HVMVSUBSTATIONCONNECTEDDELTAGROUNDEDWYE,VARNAME2,VARNAME3,VARNAME4,VARNAME5,VARNAME6,VARNAME7,VARNAME8,VARNAME9,VARNAME10,VARNAME11]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [HVMVSUBSTATIONCONNECTEDDELTAGROUNDEDWYE,VARNAME2,VARNAME3,VARNAME4,VARNAME5,VARNAME6,VARNAME7,VARNAME8,VARNAME9,VARNAME10,VARNAME11]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [HVMVSubstationconnectedDeltagroundedwye,VarName2,VarName3,VarName4,VarName5,VarName6,VarName7,VarName8,VarName9,VarName10,VarName11] = importfile('Transformers.csv',2, 3);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/04/20 17:22:07

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: text (%s)
%   column3: text (%s)
%	column4: text (%s)
%   column5: text (%s)
%	column6: text (%s)
%   column7: text (%s)
%	column8: text (%s)
%   column9: text (%s)
%	column10: text (%s)
%   column11: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Name= dataArray{1}{2};
phases= dataArray{2}{2};
bus1= dataArray{3}{2};
bus2= dataArray{4}{2};
kV_pri = dataArray{5}{2};
kV_sec = dataArray{6}{2};
MVA= dataArray{7}{2};
Conn_pri = dataArray{8}{2};
Conn_sec= dataArray{9}{2};
XHL = dataArray{10}{2};
RHL = dataArray{11}{2};


